---

- name: ZOOKEEPER | Install
  import_tasks: install.yml
  tags:
    - install

- name: ZOOKEEPER | Configure
  import_tasks: config.yml
  tags:
    - configure

- name: ZOOKEEPER | Service
  import_tasks: service.yml
  tags:
    - service
